=== AdiStar350/full_stack_project_2025/animal_db_xml_files/animals_tb_xml/animals.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT database (table)>
<!ATTLIST database name CDATA #REQUIRED>

<!ELEMENT table (columns, data)>
<!ATTLIST table name CDATA #REQUIRED>

<!ELEMENT columns (column*)>
<!ELEMENT column EMPTY>
<!ATTLIST column
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    nullable CDATA #REQUIRED
    auto_increment CDATA #IMPLIED
    foreign_key CDATA #IMPLIED>

<!ELEMENT data (row*)>
<!ELEMENT row EMPTY>
<!ATTLIST row
    animal_id CDATA #REQUIRED
    name CDATA #REQUIRED
    birth_year CDATA #REQUIRED
    habitat CDATA #IMPLIED
    lifespan CDATA #IMPLIED
    type_id CDATA #IMPLIED>

=== AdiStar350/full_stack_project_2025/animal_db_xml_files/animals_tb_xml/animals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE database SYSTEM "animals.dtd"> -->
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="animals.xsd" name="animals_db">
    <table name="animals">
        <columns>
            <column name="animal_id" type="int" nullable="false" auto_increment="true" />
            <column name="name" type="varchar(100)" nullable="false" />
            <column name="birth_year" type="int" nullable="false" />
            <column name="habitat" type="varchar(100)" nullable="true" />
            <column name="lifespan" type="int" nullable="true" />
            <column name="type_id" type="int" nullable="true" foreign_key="types.type_id" />
        </columns>
        <data>
            <row animal_id="1" name="Turtle" birth_year="1900" habitat="rivers" lifespan="300"
                type_id="3" />
            <row animal_id="2" name="tucan" birth_year="2009" habitat="trees" lifespan="40"
                type_id="2" />
            <row animal_id="3" name="platipus" birth_year="1983" habitat="haifa" lifespan="10"
                type_id="1" />
            <row animal_id="5" name="tiger" birth_year="2010" habitat="desert" lifespan="80"
                type_id="1" />
            <row animal_id="8" name="hippo" birth_year="2007" habitat="water" lifespan="80"
                type_id="1" />
            <row animal_id="9" name="shkimaj" birth_year="2019" habitat="poland" lifespan="30"
                type_id="1" />
        </data>
    </table>
</database>
